-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 23:36:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema solvd_laba_olympic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema solvd_laba_olympic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solvd_laba_olympic` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `solvd_laba_olympic` ;

-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`international_olympic_commitee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`international_olympic_commitee` (
  `IOC_id` TINYINT NOT NULL,
  `IOC_name` VARCHAR(45) NULL DEFAULT NULL,
  `president` VARCHAR(45) NULL DEFAULT NULL,
  `headquarter` VARCHAR(45) NULL DEFAULT NULL,
  `year_established` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IOC_id`),
  UNIQUE INDEX `IOC_ID_UNIQUE` (`IOC_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`host_country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`host_country` (
  `host_country_id` INT NOT NULL,
  `country_name` VARCHAR(45) NULL DEFAULT NULL,
  `continent` VARCHAR(45) NULL DEFAULT NULL,
  `capital_city` VARCHAR(45) NULL DEFAULT NULL,
  `year_of_host` YEAR NULL DEFAULT NULL,
  `IOC_id` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`host_country_id`),
  UNIQUE INDEX `host_country_id_UNIQUE` (`host_country_id` ASC) VISIBLE,
  INDEX `IOC_id_idx` (`IOC_id` ASC) VISIBLE,
  CONSTRAINT `host_country_ibfk_1`
    FOREIGN KEY (`IOC_id`)
    REFERENCES `solvd_laba_olympic`.`international_olympic_commitee` (`IOC_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`cities` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL DEFAULT NULL,
  `host_country_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `City_ID_UNIQUE` (`city_id` ASC) VISIBLE,
  INDEX `fk_host_country` (`host_country_id` ASC) VISIBLE,
  CONSTRAINT `fk_host_country`
    FOREIGN KEY (`host_country_id`)
    REFERENCES `solvd_laba_olympic`.`host_country` (`host_country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`hotels` (
  `hotel_id` INT NOT NULL,
  `hotel_name` VARCHAR(45) NULL DEFAULT NULL,
  `city_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`hotel_id`),
  UNIQUE INDEX `Hotel_ID_UNIQUE` (`hotel_id` ASC) VISIBLE,
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `hotels_ibfk_1`
    FOREIGN KEY (`city_id`)
    REFERENCES `solvd_laba_olympic`.`cities` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`nations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`nations` (
  `nation_id` INT NOT NULL,
  `nation_name` VARCHAR(45) NULL DEFAULT NULL,
  `region` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nation_id`),
  UNIQUE INDEX `Nation_ID_UNIQUE` (`nation_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`teams` (
  `team_id` INT NOT NULL,
  `team_name` VARCHAR(45) NOT NULL,
  `nation_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  PRIMARY KEY (`team_id`),
  UNIQUE INDEX `team_id_UNIQUE` (`team_id` ASC) VISIBLE,
  INDEX `nation_id_idx` (`nation_id` ASC) VISIBLE,
  INDEX `fk_teams_hotels1_idx` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT `fk_hotels1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `solvd_laba_olympic`.`hotels` (`hotel_id`),
  CONSTRAINT `fk_nation_id`
    FOREIGN KEY (`nation_id`)
    REFERENCES `solvd_laba_olympic`.`nations` (`nation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`athletes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`athletes` (
  `athlete_id` INT NOT NULL,
  `athlete_name` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `age` INT NULL DEFAULT NULL,
  `team_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`athlete_id`),
  UNIQUE INDEX `athlete_id_UNIQUE` (`athlete_id` ASC) VISIBLE,
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `athletes_ibfk_1`
    FOREIGN KEY (`team_id`)
    REFERENCES `solvd_laba_olympic`.`teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`sports` (
  `sport_id` INT NOT NULL,
  `sport_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sport_id`),
  UNIQUE INDEX `sport_id_UNIQUE` (`sport_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`locations` (
  `location_id` INT NOT NULL,
  `location_name` VARCHAR(45) NOT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`location_id`),
  UNIQUE INDEX `Stadium_id_UNIQUE` (`location_id` ASC) VISIBLE,
  INDEX `city_id` (`city_id` ASC) VISIBLE,
  CONSTRAINT `locations_ibfk_1`
    FOREIGN KEY (`city_id`)
    REFERENCES `solvd_laba_olympic`.`cities` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`events` (
  `event_id` INT NOT NULL,
  `event_name` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `sport_id` INT NULL DEFAULT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE,
  INDEX `sport_id_idx` (`sport_id` ASC) VISIBLE,
  INDEX `fk_events_stadiums1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `events_ibfk_1`
    FOREIGN KEY (`sport_id`)
    REFERENCES `solvd_laba_olympic`.`sports` (`sport_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_location_id`
    FOREIGN KEY (`location_id`)
    REFERENCES `solvd_laba_olympic`.`locations` (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`broadcasting_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`broadcasting_schedule` (
  `broadcast_id` INT NOT NULL,
  `channel` VARCHAR(45) NULL DEFAULT NULL,
  `broadcast_date` DATE NULL DEFAULT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  `even_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`broadcast_id`),
  UNIQUE INDEX `broadcast_ID_UNIQUE` (`broadcast_id` ASC) VISIBLE,
  INDEX `even_id` (`even_id` ASC) VISIBLE,
  CONSTRAINT `broadcasting_schedule_ibfk_1`
    FOREIGN KEY (`even_id`)
    REFERENCES `solvd_laba_olympic`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`competitions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`competitions` (
  `compete_id` INT NOT NULL AUTO_INCREMENT,
  `team_id` INT NULL DEFAULT NULL,
  `event_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`compete_id`),
  INDEX `fk_team_id` (`team_id` ASC) VISIBLE,
  INDEX `fk_event_id` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `solvd_laba_olympic`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `solvd_laba_olympic`.`teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `solvd_laba_olympic`.`results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solvd_laba_olympic`.`results` (
  `result_id` INT NOT NULL,
  `medal` VARCHAR(45) NULL DEFAULT NULL,
  `record` VARCHAR(45) NULL DEFAULT NULL,
  `event_id` INT NULL DEFAULT NULL,
  `athlete_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`result_id`),
  UNIQUE INDEX `result_id_UNIQUE` (`result_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_results_athletes1_idx` (`athlete_id` ASC) VISIBLE,
  INDEX `fk_results_teams1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_athletes1`
    FOREIGN KEY (`athlete_id`)
    REFERENCES `solvd_laba_olympic`.`athletes` (`athlete_id`),
  CONSTRAINT `fk_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `solvd_laba_olympic`.`teams` (`team_id`),
  CONSTRAINT `results_ibfk_2`
    FOREIGN KEY (`event_id`)
    REFERENCES `solvd_laba_olympic`.`events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
