-- MySQL Script generated by MySQL Workbench
-- Tue May 30 00:12:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema solvd_laba_olympic


USE `solvd_laba_olympic` ;

-- -----------------------------------------------------
-- Table `International Olympic Commitee`
-- -----------------------------------------------------
CREATE TABLE `International_Olympic_Commitee` (
  `IOC_id` TINYINT NOT NULL,
  `IOC_name` VARCHAR(45) NULL,
  `president` VARCHAR(45) NULL,
  `headquarter` VARCHAR(45) NULL,
  `year_established` YEAR(4) NULL,
  PRIMARY KEY (`IOC_id`),
  UNIQUE INDEX `IOC_ID_UNIQUE` (`IOC_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Nation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Nation` (
  `nation_id` INT NOT NULL,
  `nation_name` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  PRIMARY KEY (`nation_id`),
  UNIQUE INDEX `Nation_ID_UNIQUE` (`nation_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Cities`
-- -----------------------------------------------------
CREATE TABLE `Cities` (
  `city_id` INT NOT NULL,
  `city_name` VARCHAR(45) NULL,
  `nation_id` INT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `City_ID_UNIQUE` (`city_id` ASC) VISIBLE,
  INDEX `nation_id_idx` (`nation_id` ASC) VISIBLE,
CONSTRAINT FOREIGN KEY (`nation_id`)
REFERENCES `Nation` (`nation_id`)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sports`
-- -----------------------------------------------------
CREATE TABLE `Sports` (
  `sport_id` INT NOT NULL,
  `sport_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sport_id`),
  UNIQUE INDEX `sport_id_UNIQUE` (`sport_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stadiums`
-- -----------------------------------------------------
CREATE TABLE `Stadiums` (
  `stadium_id` INT NOT NULL,
  `stadium_name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`stadium_id`),
  UNIQUE INDEX `Stadium_id_UNIQUE` (`stadium_id` ASC) VISIBLE,
  CONSTRAINT FOREIGN KEY (`city_id`)
  REFERENCES `Cities` (`city_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hotels`
-- -----------------------------------------------------
CREATE TABLE `Hotels` (
  `hotel_id` INT NOT NULL,
  `hotel_name` VARCHAR(45) NULL,
  `city_id` INT NULL,
  PRIMARY KEY (`hotel_id`),
  UNIQUE INDEX `Hotel_ID_UNIQUE` (`hotel_id` ASC) VISIBLE,
  CONSTRAINT FOREIGN KEY (`city_id`)
  REFERENCES `Cities` (`city_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Events`
-- -----------------------------------------------------
CREATE TABLE `Events` (
  `event_id` INT NOT NULL,
  `event_name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `sport_id` INT NULL,
  `start_time` TIME NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE,
  INDEX `sport_id_idx` (`sport_id` ASC) VISIBLE,
  CONSTRAINT FOREIGN KEY (`sport_id`)
  REFERENCES `Sports` (`sport_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Broadcasting_schedule`
-- -----------------------------------------------------
CREATE TABLE `Broadcasting_schedule` (
  `broadcast_id` INT NOT NULL,
  `channel` VARCHAR(45) NULL,
  `broadcast_date` DATE NULL,
  `start_time` TIME NULL,
  `end_time` TIME NULL,
  `even_id` INT NULL,
  PRIMARY KEY (`broadcast_id`),
  UNIQUE INDEX `broadcast_ID_UNIQUE` (`broadcast_id` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`even_id`)
    REFERENCES `Events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teams`
-- -----------------------------------------------------
CREATE TABLE `Teams` (
  `team_id` INT NOT NULL,
  `team_name` VARCHAR(45) NOT NULL,
  `sport_id` INT NOT NULL,
  `nation_id` INT NOT NULL,
  PRIMARY KEY (`team_id`),
  UNIQUE INDEX `team_id_UNIQUE` (`team_id` ASC) VISIBLE,
  INDEX `nation_id_idx` (`nation_id` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`sport_id`)
    REFERENCES `Sports` (`sport_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT
    FOREIGN KEY (`nation_id`)
    REFERENCES  `Nation` (`nation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Athletes`
-- -----------------------------------------------------
CREATE TABLE `Athletes` (
  `athlete_id` INT NOT NULL,
  `athlete_name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `team_id` INT NULL,
  PRIMARY KEY (`athlete_id`),
  UNIQUE INDEX `athlete_id_UNIQUE` (`athlete_id` ASC) VISIBLE,
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT
    FOREIGN KEY (`team_id`)
    REFERENCES `Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Results`
-- -----------------------------------------------------
CREATE TABLE `Results` (
  `result_id` INT NOT NULL,
  `medal` VARCHAR(45) NULL,
  `record` VARCHAR(45) NULL,
  `athlete_id` INT NULL,
  `event_id` INT NULL,
  PRIMARY KEY (`result_id`),
  UNIQUE INDEX `result_id_UNIQUE` (`result_id` ASC) VISIBLE,
  INDEX `athlete_id_idx` (`athlete_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT 
    FOREIGN KEY (`athlete_id`)
    REFERENCES `Athletes` (`athlete_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT
    FOREIGN KEY (`event_id`)
    REFERENCES `Events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Host Country`
-- -----------------------------------------------------
CREATE TABLE `Host Country` (
  `host_country_id` INT NOT NULL,
  `country_name` VARCHAR(45) NULL,
  `continent` VARCHAR(45) NULL,
  `capital_city` VARCHAR(45) NULL,
  `official_language` VARCHAR(45) NULL,
  `year_of_host` YEAR NULL,
  `IOC_id` TINYINT NULL,
  PRIMARY KEY (`host_country_id`),
  UNIQUE INDEX `host_country_id_UNIQUE` (`host_country_id` ASC) VISIBLE,
  INDEX `IOC_id_idx` (`IOC_id` ASC) VISIBLE,
  CONSTRAINT FOREIGN KEY (`IOC_id`)
REFERENCES `international_olympic_commitee` (`IOC_id`)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
