-- MySQL Script generated by MySQL Workbench
-- Mon May 29 16:46:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`International Olympic Commitee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`International Olympic Commitee` (
  `IOC_id` TINYINT NOT NULL AUTO_INCREMENT,
  `IOC_name` VARCHAR(45) NOT NULL,
  `president` VARCHAR(45) NOT NULL,
  `headquarter` VARCHAR(45) NOT NULL,
  `year_established` YEAR(4) NOT NULL,
  PRIMARY KEY (`IOC_id`),
  UNIQUE INDEX `IOC_ID_UNIQUE` (`IOC_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nation` (
  `nation_id` INT NOT NULL AUTO_INCREMENT,
  `nation_name` VARCHAR(45) NOT NULL,
  `region` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nation_id`),
  UNIQUE INDEX `Nation_ID_UNIQUE` (`nation_id` ASC) VISIBLE,
  UNIQUE INDEX `Nation_name_UNIQUE` (`nation_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cities` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `nation_id` INT NOT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `City_ID_UNIQUE` (`city_id` ASC) VISIBLE,
  UNIQUE INDEX `Nation_ID_UNIQUE` (`nation_id` ASC) VISIBLE,
  CONSTRAINT `nation_id`
    FOREIGN KEY (`nation_id`)
    REFERENCES `mydb`.`Nation` (`nation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sports` (
  `sport_id` INT NOT NULL AUTO_INCREMENT,
  `sport_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sport_id`),
  UNIQUE INDEX `Sport_ID_UNIQUE` (`sport_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stadiums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stadiums` (
  `stadium_id` INT NOT NULL AUTO_INCREMENT,
  `stadium_name` VARCHAR(45) NOT NULL,
  `capacity` INT NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`stadium_id`),
  UNIQUE INDEX `Stadium_id_UNIQUE` (`stadium_id` ASC) VISIBLE,
  UNIQUE INDEX `City_ID_UNIQUE` (`city_id` ASC) VISIBLE,
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`Cities` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Hotels` (
  `hotel_id` INT NOT NULL AUTO_INCREMENT,
  `hotel_name` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`hotel_id`),
  UNIQUE INDEX `Hotel_ID_UNIQUE` (`hotel_id` ASC) VISIBLE,
  UNIQUE INDEX `City_ID_UNIQUE` (`city_id` ASC) VISIBLE,
  CONSTRAINT `city_id`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`Cities` (`city_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `sport_id` INT NOT NULL,
  `start_time` TIME NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE,
  INDEX `sport_id_idx` (`sport_id` ASC) VISIBLE,
  CONSTRAINT `sport_id`
    FOREIGN KEY (`sport_id`)
    REFERENCES `mydb`.`Sports` (`sport_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Broadcasting_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Broadcasting_schedule` (
  `broadcast_id` INT NOT NULL AUTO_INCREMENT,
  `channel` VARCHAR(45) NOT NULL,
  `broadcast_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `even_id` INT NOT NULL,
  PRIMARY KEY (`broadcast_id`),
  UNIQUE INDEX `broadcast_ID_UNIQUE` (`broadcast_id` ASC) VISIBLE,
  UNIQUE INDEX `even_id_UNIQUE` (`even_id` ASC) VISIBLE,
  CONSTRAINT `event_id`
    FOREIGN KEY (`even_id`)
    REFERENCES `mydb`.`Events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teams` (
  `team_id` INT NOT NULL AUTO_INCREMENT,
  `team_name` VARCHAR(45) NOT NULL,
  `sport_id` INT NOT NULL,
  `nation_id` INT NOT NULL,
  PRIMARY KEY (`team_id`),
  UNIQUE INDEX `team_id_UNIQUE` (`team_id` ASC) VISIBLE,
  UNIQUE INDEX `sport_id_UNIQUE` (`sport_id` ASC) VISIBLE,
  INDEX `nation_id_idx` (`nation_id` ASC) VISIBLE,
  CONSTRAINT `sport_id`
    FOREIGN KEY (`sport_id`)
    REFERENCES `mydb`.`Sports` (`sport_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `nation_id`
    FOREIGN KEY (`nation_id`)
    REFERENCES `mydb`.`Nation` (`nation_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Athletes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Athletes` (
  `athlete_id` INT NOT NULL AUTO_INCREMENT,
  `athlete_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `age` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`athlete_id`),
  UNIQUE INDEX `athlete_id_UNIQUE` (`athlete_id` ASC) VISIBLE,
  INDEX `team_id_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `team_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `mydb`.`Teams` (`team_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Results` (
  `result_id` INT NOT NULL AUTO_INCREMENT,
  `medal` VARCHAR(45) NOT NULL,
  `record` VARCHAR(45) NOT NULL,
  `athlete_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`result_id`),
  UNIQUE INDEX `result_id_UNIQUE` (`result_id` ASC) VISIBLE,
  INDEX `athlete_id_idx` (`athlete_id` ASC) VISIBLE,
  INDEX `event_id_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `athlete_id`
    FOREIGN KEY (`athlete_id`)
    REFERENCES `mydb`.`Athletes` (`athlete_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`Events` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Host Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Host Country` (
  `host_country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  `continent` VARCHAR(45) NOT NULL,
  `capital_city` VARCHAR(45) NOT NULL,
  `official_language` VARCHAR(45) NOT NULL,
  `year_of_host` YEAR NOT NULL,
  `IOC_id` TINYINT NOT NULL,
  PRIMARY KEY (`host_country_id`),
  UNIQUE INDEX `host_country_id_UNIQUE` (`host_country_id` ASC) VISIBLE,
  INDEX `IOC_id_idx` (`IOC_id` ASC) VISIBLE,
  CONSTRAINT `IOC_id`
    FOREIGN KEY (`IOC_id`)
    REFERENCES `mydb`.`International Olympic Commitee` (`IOC_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
